version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      # - ./node_modules:/usr/src/app/node_modules
      - ./.env:/usr/src/app/.env
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start 

networks:
  default:
    name: proxy
    external: true